### PR TITLE
Remove numpy as a dependency

### PR DESCRIPTION
**Pull request by Lonami**
Literally why

### CODE REVIEW

**Comment by Snektron** [comment]
Numpy is probably more performant than the std random, which obviously is important here

**Comment by Lonami** [comment]
You do know how big of an *external dependency* numpy is when all you need is a RNG, right?

**Comment by Snektron** [comment]
Numpy is pretty much the python standard library anyway.

**Comment by brentmaas** [comment]
The astronomical community will probably exile me now lol

**Comment by Lonami** [comment]
Yay, I did it. Thank you for merging.

**Pull request merged**
